# Generated by Django 2.2.9 on 2020-02-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('start', models.DateTimeField(verbose_name='meet start time')),
                ('end', models.DateTimeField(verbose_name='meet end time')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_model.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_state', models.IntegerField(default=0)),
                ('sign_time', models.DateTimeField(verbose_name='sign time')),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_model.Meet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_model.User')),
            ],
        ),
        migrations.AddField(
            model_name='meet',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='base_model.User'),
        ),
        migrations.AddField(
            model_name='meet',
            name='participant',
            field=models.ManyToManyField(related_name='participant', to='base_model.User'),
        ),
        migrations.AddField(
            model_name='meet',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_model.Room'),
        ),
    ]
