# Generated by Django 3.0.2 on 2020-02-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('start', models.DateTimeField(verbose_name='meet start time')),
                ('end', models.DateTimeField(verbose_name='meet end time')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wechat_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_model.Group')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_model.User')),
            ],
            bases=('base_model.user',),
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_state', models.IntegerField(default=0)),
                ('sign_time', models.DateTimeField(verbose_name='sign time')),
                ('meet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_model.Meet')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_model.User')),
            ],
        ),
        migrations.AddField(
            model_name='meet',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_model.Room'),
        ),
        migrations.AddField(
            model_name='meet',
            name='organizer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_model.SuperUser'),
        ),
    ]
